export const REQUEST_COMICS = 'REQUEST_COMICS';
export const REQUEST_COMIC = 'REQUEST_COMIC';
export const RECEIVE_COMICS = 'RECEIVE_COMICS';
export const RECEIVE_COMIC = 'RECEIVE_COMIC';
export const RESET_COMIC = 'RESET_COMIC';
export const ERROR_REQUEST_COMIC = 'ERROR_REQUEST_COMIC';
export const RECEIVE_MORE_COMICS = 'RECEIVE_MORE_COMICS';
export const RESET_COMIC_LIST = 'RESET_COMIC_LIST';
